#!/bin/bash

# Reset
Color_Off="\033[0m"       # Text Reset

# Regular Colors
Black="\033[30m"        # Black
Red="\033[31m"          # Red
Green="\033[32m"        # Green
Yellow="\033[33m"       # Yellow
Blue="\033[34m"         # Blue
Purple="\033[35m"       # Purple
Cyan="\033[36m"         # Cyan
White="\033[37m"        # White

black(){
    echo "${Black}$1${Color_Off}"
}

red(){
    echo "${Red}$1${Color_Off}"
}

green(){
    echo "${Green}$1${Color_Off}"
}

yellow(){
    echo "${Yellow}$1${Color_Off}"
}

blue(){
    echo "${Blue}$1${Color_Off}"
}

purple(){
    echo "${Purple}$1${Color_Off}"
}

cyan(){
    echo "${Cyan}$1${Color_Off}"
}

white(){
    echo "${White}$1${Color_Off}"
}

# Bold
BBlack="\033[1;30m"     # Black
BRed="\033[1;31m"       # Red
BGreen="\033[1;32m"     # Green
BYellow="\033[1;33m"    # Yellow
BBlue="\033[1;34m"      # Blue
BPurple="\033[1;35m"    # Purple
BCyan="\033[1;36m"      # Cyan
BWhite="\033[1;37m"     # White

blackb(){
    echo "${BBlack}$1${Color_Off}"
}

redb(){
    echo "${BRed}$1${Color_Off}"
}

greenb(){
    echo "${BGreen}$1${Color_Off}"
}

yellowb(){
    echo "${BYellow}$1${Color_Off}"
}

blueb(){
    echo "${BBlue}$1${Color_Off}"
}

purpleb(){
    echo "${BPurple}$1${Color_Off}"
}

cyanb(){
    echo "${BCyan}$1${Color_Off}"
}

whiteb(){
    echo "${BWhite}$1${Color_Off}"
}

# Underline
UBlack="\033[4;30m"     # Black
URed="\033[4;31m"       # Red
UGreen="\e[4;32m"       # Green
UYellow="\e[4;33m"      # Yellow
UBlue="\e[4;34m"        # Blue
UPurple="\e[4;35m"      # Purple
UCyan="\e[4;36m"        # Cyan
UWhite="\e[4;37m"       # White

blacku(){
    echo "${UBlack}$1${Color_Off}"
}

redu(){
    echo "${URed}$1${Color_Off}"
}

greenu(){
    echo "${UGreen}$1${Color_Off}"
}

yellowu(){
    echo "${UYellow}$1${Color_Off}"
}

blueu(){
    echo "${UBlue}$1${Color_Off}"
}

purpleu(){
    echo "${UPurple}$1${Color_Off}"
}

cyanu(){
    echo "${UCyan}$1${Color_Off}"
}

whiteu(){
    echo "${UWhite}$1${Color_Off}"
}

# Background
On_Black="\033[40m"     # Black
On_Red="\033[41m"       # Red
On_Green="\033[42m"     # Green
On_Yellow="\033[43m"    # Yellow
On_Blue="\033[44m"      # Blue
On_Purple="\033[45m"    # Purple
On_Cyan="\033[46m"      # Cyan
On_White="\033[47m"     # White

blackbg(){
    echo "${On_Black}$1${Color_Off}"
}

redbg(){
    echo "${On_Red}$1${Color_Off}"
}

greenbg(){
    echo "${On_Green}$1${Color_Off}"
}

yellowbg(){
    echo "${On_Yellow}$1${Color_Off}"
}

bluebg(){
    echo "${On_Blue}$1${Color_Off}"
}

purplebg(){
    echo "${On_Purple}$1${Color_Off}"
}

cyanbg(){
    echo "${On_Cyan}$1${Color_Off}"
}

whitebg(){
    echo "${On_White}$1${Color_Off}"
}

