#!/bin/bash

mv larasail-master/.larasail /etc/.larasail
echo "alias larasail='sh /etc/.larasail/larasail'" >> /etc/bash.bashrc
alias larasail='sh /etc/.larasail/larasail' >/dev/null 2>/dev/null

. /etc/.larasail/includes/colors
. /etc/.larasail/includes/format

setsailNoColor

barNoColor
echo "| Prepare the Sails, we're ready for the Open Sea!";
barNoColor

rm -rf larasail-master