#!/bin/bash

mv larasail-master/.larasail /etc/.larasail
echo "alias larasail='sh /etc/.larasail/larasail'" >> /etc/bash.bashrc

PASS=$(openssl rand -base64 32)

if [ ! -d /etc/.larasail/tmp ]; then
  sudo mkdir /etc/.larasail/tmp
fi

sudo echo $PASS > /etc/.larasail/tmp/pass

useradd -G sudo -d /home/larasail -p $PASS -m larasail
echo 'larasail ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
chown -R larasail:larasail /etc/.larasail/
chown -R larasail:larasail /var/www

. /etc/.larasail/includes/colors
. /etc/.larasail/includes/format

setsailNoColor

barNoColor
echo "| Prepare the Sails, we're ready for the Open Sea!";
barNoColor

echo "alias larasail='sh /etc/.larasail/larasail'" >> /home/larasail/.bashrc

rm -rf larasail-master

