#!/bin/bash

. ~/.larasail/colors
. ~/.larasail/format
. ~/.larasail/setsail

bar
cyan "| Installing PHP 7.1 and all necessary files";
bar

#sudo add-apt-repository ppa:ondrej/php
#sudo apt-get update
#sudo apt-get upgrade
