#!/bin/bash

. ~/.larasail/colors
. ~/.larasail/format
. ~/.larasail/setsail

bar
cyan "| Installing PHP 7.1 and all necessary files";
bar

sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get upgrade

sudo apt-get install php7.1 php7.1-common php7.1-mysql php7.1-gd php7.1-mcrypt php7.1-mysql php7.1-curl php7.1-mbstring php7.1-xml php7.1-zip php7.1-fpm curl git

sudo apt-get purge php7.0 php7.0-common

sudo rm /usr/bin/php
sudo ln -s /usr/bin/php7.1 /usr/bin/php


curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
