#!/bin/bash

cyan   "                                                  "
cyan   "                     LaraSail                     "
purple "                         _                        "
purple "                     __ )_)__                     "
purple "                     )_))_))_)                    "
purple "                     _!__!__!_                    "
purple "                     \_______/                    "
blue   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
