#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail Environment Launcher
#--------------------------------------------------------------------------
#
# Enter shell as larasail user
#
#/

if [ "$(whoami)" != "larasail" ]; then
    sudo su - larasail
else
    echo "Already logged in as larasail"
fi
