#!/bin/bash
# Include the first argument as a script

if [ "$1" = "-h" ]
then
    . /etc/.larasail/includes/help
elif [ "$1" = "host" ] ; then
	sudo sh /etc/.larasail/$1 $2 $3
else
    . /etc/.larasail/$1 $2 $3
fi