#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail Mysql Password
#--------------------------------------------------------------------------
#
# This file will display the MySQL password
#
#/

. /etc/.larasail/includes/colors
. /etc/.larasail/includes/format

setsail

MYSQLPASS=$(cat /etc/.larasail/tmp/mysqlpass)

bar
cyan "| MySQL Password:"
cyan "| $MYSQLPASS"
bar