#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail Mysql Password
#--------------------------------------------------------------------------
#
# This file will display the MySQL password
#
#/

. /etc/.larasail/includes/colors
. /etc/.larasail/includes/format

setsail

MYSQLPASS=$(cat /home/larasail/.my.cnf  | grep password | awk -F'password=' '{print $2}')

bar
cyan "| MySQL Password:"
cyan "| $MYSQLPASS"
bar
