#!/bin/bash

. /etc/.larasail/includes/colors
. /etc/.larasail/includes/format

PHP="7.2"

if [ "$1" = "php71" ]
then
   PHP="7.1"
fi

setsail


bar
cyan "| Installing Nginx ";
bar

sudo apt-get -qq update
sudo apt-get -y -qq install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo systemctl restart nginx

bar
cyan "| Installing MySQL ";
bar

MYSQLPASS=$(openssl rand -base64 32)

sudo apt-get -qq update
if [ ! -d /etc/.larasail/tmp ]; then
  mkdir /etc/.larasail/tmp
fi

echo $MYSQLPASS > /etc/.larasail/tmp/mysqlpass

RUN ['/bin/bash', '-c', 'sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password $MYSQLPASS"']
RUN ['/bin/bash', '-c', 'sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $MYSQLPASS"']
RUN ['/bin/bash', '-c', 'sudo debconf-set-selections <<< "mysql-server-5.7 mysql-server/root_password password $MYSQLPASS"']
RUN ['/bin/bash', '-c', 'sudo debconf-set-selections <<< "mysql-server-5.7 mysql-server/root_password_again password $MYSQLPASS"']

sudo apt-get install -y -qq mysql-server

# Enable 3306 ports in order to connect to database via Sequel Pro
enable port 3306
sudo ufw allow from 15.15.15.0/24 to any port 3306


bar
cyan "| Installing PHP $PHP and all necessary files";
bar

sudo apt-get -qq update
sudo apt-get install -y -qq language-pack-en-base
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
sudo apt-get install -y -qq software-properties-common
sudo add-apt-repository -y -qq ppa:ondrej/php
sudo apt-get -y -qq update
sudo apt-get -y -qq upgrade

#required for PHP7.2 mcrypt
sudo apt-get -y -qq install gcc make autoconf libc-dev pkg-config
sudo apt-get -y -qq install libmcrypt-dev


sudo apt-get install -y -qq php
sudo apt-get install -y -qq php7.1-mcrypt
sudo apt-get install -y -qq php$PHP php$PHP-common php$PHP-mysql php$PHP-gd php$PHP-mysql php$PHP-curl php$PHP-mbstring php$PHP-xml php$PHP-zip php$PHP-fpm curl git

sudo rm /usr/bin/php
sudo ln -s /usr/bin/php$PHP /usr/bin/php

bar
cyan "| Installing Composer ";
bar

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

bar
cyan "| Adding the Laravel Installer "
bar

composer global require "laravel/installer"
