#!/bin/bash

. ~/.larasail/includes/colors
. ~/.larasail/includes/format

PHP="7.2"

if [ "$1" = "--php71" ]
then
   PHP="7.1"
fi

setail

bar
cyan "| Installing Nginx ";
bar

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo systemctl restart nginx

bar
cyan "| Installing PHP $PHP and all necessary files";
bar

apt-get update &&
apt-get install -y language-pack-en-base &&
export LC_ALL=en_US.UTF-8 &&
export LANG=en_US.UTF-8 &&
apt-get install -y software-properties-common &&
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get install php$PHP php$PHP-common php$PHP-mysql php$PHP-gd php$PHP-mcrypt php$PHP-mysql php$PHP-curl php$PHP-mbstring php$PHP-xml php$PHP-zip php$PHP-fpm curl git

sudo rm /usr/bin/php
sudo ln -s /usr/bin/php$PHP /usr/bin/php

bar
cyan "| Installing Composer ";
bar

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

