#!/bin/bash

#/
#--------------------------------------------------------------------------
# Larasail Initial Setup
#--------------------------------------------------------------------------
#
# This file will setup the server with Nginx, PHP, and Mysql.
#
#/

. /etc/.larasail/includes/colors
. /etc/.larasail/includes/format

PHP="7.2"

if [ "$1" = "php71" ]
then
   PHP="7.1"
fi

setsail


bar
cyan "| Installing Nginx ";
bar

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo systemctl restart nginx

bar
cyan "| Installing MySQL ";
bar

MYSQLPASS=$(openssl rand -base64 32)

sudo apt-get update
if [ ! -d /etc/.larasail/tmp ]; then
  mkdir /etc/.larasail/tmp
fi

echo $MYSQLPASS > /etc/.larasail/tmp/mysqlpass


echo "mysql-server mysql-server/root_password password $MYSQLPASS" | sudo debconf-set-selections
echo "mysql-server mysql-server/root_password_again password $MYSQLPASS" | sudo debconf-set-selections
echo "mysql-server-5.7 mysql-server/root_password password $MYSQLPASS" | sudo debconf-set-selections
echo "mysql-server-5.7 mysql-server/root_password_again password $MYSQLPASS" | sudo debconf-set-selections

sudo apt-get install -y mysql-server

# Enable 3306 ports in order to connect to database via Sequel Pro
enable port 3306
sudo ufw allow from 15.15.15.0/24 to any port 3306


bar
cyan "| Installing PHP $PHP and all necessary files";
bar

sudo apt-get update
sudo apt-get install -y language-pack-en-base
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get -y update
sudo apt-get -y upgrade

#required for PHP7.2 mcrypt
sudo apt-get -y install gcc make autoconf libc-dev pkg-config
sudo apt-get -y install libmcrypt-dev


sudo apt-get install -y php
sudo apt-get install -y php7.1-mcrypt
sudo apt-get install -y php$PHP php$PHP-common php$PHP-mysql php$PHP-gd php$PHP-mysql php$PHP-curl php$PHP-mbstring php$PHP-xml php$PHP-zip php$PHP-fpm curl git

sudo rm /usr/bin/php
sudo ln -s /usr/bin/php$PHP /usr/bin/php

bar
cyan "| Updating Permissions "
bar

sudo chown -R larasail:larasail /var/www

bar
cyan "| Installing Composer ";
bar

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

bar
cyan "| Adding the Laravel Installer "
bar

sudo chown -R $USER:$USER ~/.composer/
composer global require "laravel/installer"

bar
cyan "| Installing certbot ";
bar

sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install python-certbot-nginx

setsail

bar
cyan "| Happy Sailing! "
bar

